#!/usr/bin/bash

#Copyright (C) 2022 Серый MLGamer <Seriy-MLGamer@yandex.ru>

#This file is part of Pixic.
#Pixic is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#Pixic is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#You should have received a copy of the GNU General Public License along with Pixic. If not, see <https://www.gnu.org/licenses/>.

if [ $OS = Windows_NT ]
then command=pixilang_console
else command=pixilang
fi
command+=" boot.pixi bash"
if [ "$TEMP" ]
then command+=" \"$TEMP\""
else command+=" -"
fi
for ((a=0; a<=$#; a++))
do
	argument=${*:$a:1}
	for ((b=0; $b!=${#argument}; b++))
	do
		if [ ${argument:$b:1} = \" ] || [ ${argument:$b:1} = $ ] || [ ${argument:$b:1} = \\ ]
		then
			argument=${argument:0:$b}\\${argument:$b}
			((b++))
		fi
	done
	command+=" \"$argument\""
done
eval $command